name: PhpUnit Coverage Percentage Badge
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci]')"

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [ '8.4' ]

    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.operating-system}}

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Show dir
        run: pwd

      - name: PHP Version
        run: php --version

      - name: Generate test coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: 'badge-coverage.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
