name: Enforce PR Label

on:
  pull_request:
    types: [opened, edited, unlabeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request?.labels || [];
            if (labels.length === 0) {
              throw new Error('This pull request must have at least one label.');
            }
