name: Enforce PR Label

on:
  pull_request:
    types: [opened, edited, unlabeled]
  push:
    branches:
      - '**'

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels;
            if (labels.length === 0) {
              throw new Error('This pull request must have at least one label.');
            }
      - name: Comment on missing labels
        if: failure()
        uses: actions/github-script@v6
        with:
            script: |
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'This pull request must have at least one label.'
              })
